/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// F446RE Microcontroller Main Program




#include "main.h"

int compute_speed(int distance) // example function
{
    if (distance < 20)
    {
        return 0;   // stop
    }
    else if (distance < 50)
    {
        return 40;  // slow
    }
    else
    {
        return 80;  // fast
    }
}

int main() {
	SystemInit();
	uart2_tx_init();
	CAN_init();

	printf("[INIT] SYSTEM STARTED\n\r");

//	while(1){
//		printf("[LOOP] RUNNING...\n\r");
//		for (volatile int i = 0; i < 2000000; i++); // Simple delay loop
//	}

//	int distance = 0;
//
//	while(1){
////		printf("[LOOP] RUNNING...\n\r");
////		for (volatile int i = 0; i < 10000000; i++); // Simple delay loop
//		DEBUG_PRINT("[SENSOR] Distance: %d\r\n", distance);
//
//		distance += 10;
//
//		if (distance > 100) {
//			distance = 0; // Reset distance for demonstration
//		}
//
//		delay(500000);
//	}



//	while (1)
//	{
//	    uint8_t distance = CAN_receive();
//
//	    DEBUG_PRINT("[MOTOR] Received: %d\r\n", distance);
//
//	    int speed = compute_speed(distance);
//
//	    DEBUG_PRINT("[MOTOR] Speed: %d\r\n", speed);
//	}
}


void delay(volatile int count) {
    while (count--) {
        __asm__("nop");
    }
}

