/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Joshua Cho
 * @brief          : Udemy Course Embedded Systems Bare Metal Programming
 * 					 Ground up
 ******************************************************************************
 **/
#include <stdint.h>

#define PERIPH_BASE					(0x40000000UL)

#define AHB1PERIPH_OFFSET			(0X00020000UL)
#define AHB1PERIPH_BASE				(PERIPH_BASE + AHB1PERIPH_OFFSET)

#define GPIOA_OFFSET				(0X0000UL)
#define GPIOA_BASE					(AHB1PERIPH_BASE + GPIOA_OFFSET)

#define GPIOC_OFFSET				(0x0800UL)
#define GPIOC_BASE					(AHB1PERIPH_BASE + GPIOC_OFFSET)

#define RCC_OFFSET					(0X3800UL)
#define RCC_BASE					(AHB1PERIPH_BASE + RCC_OFFSET)


#define PIN13						(1U<<13)
#define PUSH_BUTTON					 PIN13

#define PIN5						(1U<<5)
#define LED_PIN						 PIN5

#define GPIOAEN						(1U<<0)
#define GPIOCEN						(1U<<2)


typedef struct
{
	volatile uint32_t MODER;		// GPIO port mode register, 			Address Offset: 0x00
	volatile uint32_t DUMMY[3];		// dummy to take up other registers space
	volatile uint32_t IDR; 			// GPIO port input data register,		Address Offset: 0x10
	volatile uint32_t ODR;			// GPIO port output data register, 		Address Offset: 0x14
} GPIO_TypeDef;


typedef struct
{
	volatile uint32_t DUMMY[12];
	volatile uint32_t AHB1ENR;		// RCC AHB1 peripheral clock register,	Address Offset: 0x30
} RCC_TypeDef;


#define RCC							((RCC_TypeDef*) RCC_BASE)
#define GPIOA						((GPIO_TypeDef*) GPIOA_BASE)
#define GPIOC						((GPIO_TypeDef*) GPIOC_BASE)



int main(void)
{
	/* 1. Enable Clock Access to GPIOA */
	RCC->AHB1ENR |= GPIOAEN;
	RCC->AHB1ENR |= GPIOCEN;

	/* 2a. Set PA5 as output pin */
	GPIOA->MODER |=  (1U << 10);
	GPIOA->MODER &= ~(1U << 11);

	/* 2b. Set PC13 as input pin */
	GPIOC->MODER &=	 ~(1U << 26);
	GPIOC->MODER &=  ~(1U << 27);


	while(1)
	{
		/* 3. Pushbutton to toggle LED */
		if (GPIOC->IDR & PIN13) {
			GPIOA->ODR &= ~(LED_PIN);
		}
		else {
			GPIOA->ODR |= (LED_PIN);
		}

	}
}


