/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// L475 Microcontroller Main Program




#include "main.h"

int main() {

	uart1_tx_init();
	printf("[INIT] SYSTEM STARTED\n\r");

	int distance = 100;

	while(1){
//		printf("[LOOP] RUNNING...\n\r");
//		for (volatile int i = 0; i < 10000000; i++); // Simple delay loop
		DEBUG_PRINT("[SENSOR] Distance: %d\r\n", distance);

		distance -= 10;

		if (distance < 0) {
			distance = 100; // Reset distance for demonstration
		}

		delay(500000);
	}
}


void delay(volatile int count) {
    while (count--) {
        __asm__("nop");
    }
}
