/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// L475 Microcontroller Main Program




#include "main.h"
#include "system_stm32l4xx.h"

int main() {
	printf("[INIT] SYSTEM STARTED\n\r");
	System_Init();
	uart1_tx_init();
//	CAN_init();
//	CAN_loopback(); // Enable loopback mode for testing
//	CAN_loopback_off(); // Disable loopback mode for normal operation
//	CAN_start();
	i2c_init();
	delay(1000000); // Short delay to ensure everything is initialized before starting the main loop
	printf("[L475] STARTED...\n\r");
	printf("[L475] READING BH1750...\n\r");

	printf("RESET I2C:\n\r");
	i2c_reset();

	/* BH1750*/
//	i2c_write(0x23, 0x10);
//
//	delay(2000000); // wait for first measurement
//
//	while (1)
//	{
//	    uint16_t raw = bh1750_read();
////	    float lux = raw / 1.2;
//
//	    printf("Lux: %d\n\r", raw);
//
//	    delay(1000000);
//	}




	printf("VL53 INIT...\n\r");
	VL53L0X_Init();

	while (1)
	{
		uint16_t dist = VL53L0X_ReadDistance();

		printf("Distance: %d mm\n\r", dist);

		delay(500000);
	}


	/* i2c bus scan */
//	while(1){
//		i2c_bus_scan();
//		delay(5000000);
//	}






//	uint8_t distance = 5;

//	while (1){
//		CAN_send_test(&distance);
//		printf("[L475] Sent: %d\r\n", distance);
//		delay(5000000);
//	}

//	uint8_t distance = 5;
//	uint8_t rx;
//	while (1)
//	{
//		printf("[LOOP] RUNNING...\n\r");
//		CAN_send(&distance);
//
//		if (CAN_receive(&rx)){
//			printf("[CAN] Received: %d\r\n", rx);
//		}
//
//	    delay(5000000);
//	}
}


void delay(volatile int count) {
    while (count--) {
        __asm__("nop");
    }
}
