/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// L475 Microcontroller Main Program




#include "main.h"
#include "system_stm32l4xx.h"
int main() {

	System_Init();
	uart1_tx_init();
	CAN_init();
	CAN_loopback(); // Enable loopback mode for testing
//	CAN_loopback_off(); // Disable loopback mode for normal operation
	CAN_start();
	delay(1000000); // Short delay to ensure everything is initialized before starting the main loop
	printf("[INIT] SYSTEM STARTED\n\r");

//	int distance = 100;
//
//	while(1){
////		printf("[LOOP] RUNNING...\n\r");
////		for (volatile int i = 0; i < 10000000; i++); // Simple delay loop
//		DEBUG_PRINT("[SENSOR] Distance: %d\r\n", distance);
//
//		distance -= 10;
//
//		if (distance < 0) {
//			distance = 100; // Reset distance for demonstration
//		}
//
//		delay(500000);
//	}
//	uint8_t distance = 100;
	uint8_t distance = 5;
	uint8_t rx;
	while (1)
	{
		printf("[LOOP] RUNNING...\n\r");
		CAN_send(&distance);

		if (CAN_receive(&rx)){
			printf("[CAN] Received: %d\r\n", rx);
		}
//		DEBUG_PRINT("Before Send");
//	    CAN_send(&distance);
//	    DEBUG_PRINT("After Send");

//	    DEBUG_PRINT("[SENSOR] Sent: %d\r\n", distance);

//	    distance--;
//
//	    if (distance == 0)
//	        distance = 100;

	    delay(5000000);
	}
}


void delay(volatile int count) {
    while (count--) {
        __asm__("nop");
    }
}
